import { Patient, Medication, AIAnalysisResult, DrugMonograph } from '../types';

/**
 * Fetches dynamic clinical drug monograph generated by Gemini 2.5 Flash
 */
export async function fetchDrugMonographFromGemini(query: string): Promise<DrugMonograph> {
  try {
    const res = await fetch('/api/drug-lookup', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ query })
    });

    if (!res.ok) {
      return {
        isFound: false,
        errorMessage: 'Drug information not available.'
      };
    }

    const data = await res.json();
    if (data.success && data.monograph) {
      return data.monograph;
    }

    return {
      isFound: false,
      errorMessage: 'Drug information not available.'
    };
  } catch (error) {
    console.error('Error fetching drug monograph:', error);
    return {
      isFound: false,
      errorMessage: 'Drug information not available.'
    };
  }
}


/**
 * Analyzes ICU Patient prescriptions for drug-drug interactions, Cockcroft-Gault renal dose adjustments,
 * duplicate therapeutic classes, contraindications, and clinical monitoring recommendations.
 */
export async function analyzePrescriptionsWithGemini(
  patient: Patient,
  medications: Medication[],
  pharmacistName: string
): Promise<AIAnalysisResult> {
  // Calculate Cockcroft-Gault CrCl
  const isMale = patient.gender === 'Male';
  const heightInches = patient.heightCm / 2.54;
  const ibw = isMale ? 50 + 2.3 * (heightInches - 60) : 45.5 + 2.3 * (heightInches - 60);
  let dosingWeight = patient.weightKg;
  if (patient.weightKg > 1.2 * ibw) {
    dosingWeight = ibw + 0.4 * (patient.weightKg - ibw);
  }
  const calculatedCrCl = Math.round(
    (((140 - patient.age) * dosingWeight) / (72 * (patient.serumCreatinine || 1.0))) * (isMale ? 1 : 0.85)
  );
  const calculatedIBW = Math.round(ibw);
  const calculatedAdjBW = Math.round(ibw + 0.4 * (patient.weightKg - ibw));

  const interactions: AIAnalysisResult['drugInteractions'] = [];
  const renalAdjustments: AIAnalysisResult['renalDoseAdjustments'] = [];
  const duplicateTherapies: AIAnalysisResult['duplicateTherapies'] = [];
  const contraindications: AIAnalysisResult['contraindications'] = [];
  const monitoringPlan: AIAnalysisResult['monitoringPlan'] = [];
  const patientCounseling: AIAnalysisResult['patientCounseling'] = [];
  const clinicalRecommendations: AIAnalysisResult['clinicalRecommendations'] = [];

  const medNames = medications.map((m) => m.name.toLowerCase());

  // Rule 1: Nephrotoxic / Ototoxic Interaction
  if (medNames.some((m) => m.includes('vancomycin')) && medNames.some((m) => m.includes('gentamicin') || m.includes('amikacin') || m.includes('colistin'))) {
    interactions.push({
      drugs: ['Vancomycin', 'Gentamicin / Aminoglycoside'],
      severity: 'Critical',
      mechanism: 'Synergistic nephrotoxicity and ototoxicity via acute tubular necrosis and vestibular cell damage.',
      clinicalEffect: 'Accelerated drop in GFR, elevated serum creatinine, potential permanent hearing loss.',
      recommendation: 'Monitor daily serum creatinine and Vancomycin AUC/MIC. Target trough 15-20 mcg/mL or consider switching to Daptomycin.'
    });
  }

  if (medNames.some((m) => m.includes('vancomycin')) && medNames.some((m) => m.includes('piperacillin') || m.includes('zosyn'))) {
    interactions.push({
      drugs: ['Vancomycin', 'Piperacillin-Tazobactam (Zosyn)'],
      severity: 'High',
      mechanism: 'Increased incidence of acute kidney injury (AKI) compared to Vancomycin alone in ICU settings.',
      clinicalEffect: 'Doubled rate of AKI onset in critically ill adults.',
      recommendation: 'Evaluate renal function daily. Consider switching Zosyn to Cefepime or Meropenem if AKI develops.'
    });
  }

  // Rule 2: QTc Prolongation
  const qtcDrugs = medications.filter((m) =>
    ['amiodarone', 'haloperidol', 'levofloxacin', 'ciprofloxacin', 'fluconazole', 'ondansetron', 'azithromycin'].some((q) =>
      m.name.toLowerCase().includes(q)
    )
  );
  if (qtcDrugs.length >= 2) {
    interactions.push({
      drugs: qtcDrugs.map((m) => m.name),
      severity: 'High',
      mechanism: 'Additive cardiac repolarization delay (IKr channel block), elevating risk of Torsades de Pointes (TdP).',
      clinicalEffect: 'Ventricular arrhythmia or sudden cardiac death.',
      recommendation: 'Obtain daily 12-lead ECG and maintain serum potassium > 4.0 mEq/L and magnesium > 2.0 mg/dL.'
    });
  }

  // Rule 3: Renal Clearance Adjustments
  if (calculatedCrCl < 50) {
    medications.forEach((m) => {
      const name = m.name.toLowerCase();
      if (name.includes('meropenem') && calculatedCrCl < 30) {
        renalAdjustments.push({
          drug: m.name,
          currentDose: m.dose + ' ' + m.frequency,
          calculatedCrCl,
          recommendedDose: '1000 mg IV q24h (or 500 mg IV q12h)',
          rationale: `CrCl is ${calculatedCrCl} mL/min. Unadjusted Meropenem accumulates, increasing risk of neurotoxicity/seizures.`
        });
      } else if (name.includes('vancomycin') && calculatedCrCl < 40) {
        renalAdjustments.push({
          drug: m.name,
          currentDose: m.dose + ' ' + m.frequency,
          calculatedCrCl,
          recommendedDose: '1000 mg IV q24h-q48h based on trough levels',
          rationale: `CrCl is ${calculatedCrCl} mL/min. Vancomycin clearance is proportional to GFR.`
        });
      } else if (name.includes('cefepime') && calculatedCrCl < 30) {
        renalAdjustments.push({
          drug: m.name,
          currentDose: m.dose + ' ' + m.frequency,
          calculatedCrCl,
          recommendedDose: '1000 mg IV q24h',
          rationale: `CrCl is ${calculatedCrCl} mL/min. Risk of Cefepime-induced encephalopathy.`
        });
      } else if (name.includes('enoxaparin') || name.includes('lovenox')) {
        if (calculatedCrCl < 30) {
          renalAdjustments.push({
            drug: m.name,
            currentDose: m.dose + ' ' + m.frequency,
            calculatedCrCl,
            recommendedDose: '30 mg SC q24h (or switch to Unfractionated Heparin)',
            rationale: `LMWH accumulates in severe renal impairment (CrCl < 30 mL/min), elevating major bleeding risk.`
          });
        }
      }
    });
  }

  // Rule 4: Duplicate Therapies
  const ppiCount = medications.filter((m) =>
    ['pantoprazole', 'omeprazole', 'esomeprazole', 'famotidine', 'ranitidine'].some((p) =>
      m.name.toLowerCase().includes(p)
    )
  );
  if (ppiCount.length >= 2) {
    duplicateTherapies.push({
      drugClass: 'Gastric Acid Suppressants / Stress Ulcer Prophylaxis',
      drugs: ppiCount.map((m) => m.name),
      recommendation: 'Discontinue duplicate agent. Single H2RA or PPI is sufficient for ICU stress ulcer prophylaxis.'
    });
  }

  const sedatives = medications.filter((m) =>
    ['propofol', 'midazolam', 'dexmedetomidine', 'lorazepam'].some((s) =>
      m.name.toLowerCase().includes(s)
    )
  );
  if (sedatives.length >= 2) {
    duplicateTherapies.push({
      drugClass: 'ICU Sedative Agents',
      drugs: sedatives.map((m) => m.name),
      recommendation: 'Titrate to RASS target (-1 to -2). Consider spontaneous awakening trials (SAT) daily.'
    });
  }

  // Rule 5: Contraindications
  if (patient.allergies) {
    patient.allergies.forEach((allergy) => {
      const allergyLower = allergy.toLowerCase();
      medications.forEach((m) => {
        if (m.name.toLowerCase().includes(allergyLower)) {
          contraindications.push({
            drug: m.name,
            conditionOrLab: `Documented severe allergy to ${allergy}`,
            severity: 'Critical',
            recommendation: `Discontinue ${m.name} immediately and substitute with an alternative class.`
          });
        }
      });
    });
  }

  // Monitoring Plan Items
  monitoringPlan.push({
    parameter: 'Renal Function & Electrolytes',
    targetRange: 'Serum Cr ≤ 1.2 mg/dL, CrCl Target > 50 mL/min',
    frequency: 'Daily (Q24H)',
    rationale: 'Monitor for acute kidney injury and drug accumulation.'
  });
  monitoringPlan.push({
    parameter: 'Vancomycin Serum Trough Level',
    targetRange: '15-20 mcg/mL for severe ICU infections',
    frequency: 'Prior to 4th dose',
    rationale: 'Ensure therapeutic efficacy while preventing ototoxicity/nephrotoxicity.'
  });

  // Patient Counseling
  if (medications.length > 0) {
    patientCounseling.push({
      drug: medications[0].name,
      keyPoints: [
        'Inform patient or family on infusion rates and potential mild side effects.',
        'Monitor for signs of hypersensitivity, rash, or changes in urine output.'
      ]
    });
  }

  // Clinical Recommendations
  clinicalRecommendations.push({
    priority: 'High',
    actionItem: 'Perform Cockcroft-Gault Renal Dosing Adjustment',
    rationale: `Calculated CrCl is ${calculatedCrCl} mL/min based on AdjBW (${calculatedAdjBW} kg). Adjust renal clearance regimens.`
  });
  if (interactions.length > 0) {
    clinicalRecommendations.push({
      priority: 'Urgent',
      actionItem: 'Resolve Critical Drug-Drug Interaction',
      rationale: `${interactions[0].drugs.join(' + ')} interaction requires immediate monitoring or drug substitution.`
    });
  }
  clinicalRecommendations.push({
    priority: 'Medium',
    actionItem: 'Daily ICU Pharmacotherapy Re-evaluation',
    rationale: 'Review antimicrobial stewardship duration of therapy and de-escalate based on culture sensitivities.'
  });

  // Calculate Overall Severity Tiers
  let overallSeverity: AIAnalysisResult['overallSeverity'] = 'Low';
  if (contraindications.length > 0 || interactions.some((i) => i.severity === 'Critical')) {
    overallSeverity = 'Critical';
  } else if (interactions.some((i) => i.severity === 'High') || renalAdjustments.length > 0) {
    overallSeverity = 'High';
  } else if (interactions.length > 0 || duplicateTherapies.length > 0) {
    overallSeverity = 'Moderate';
  }

  const summary = `Comprehensive ICU clinical review completed for ${patient.name} (MRN: ${patient.mrn}). Estimated Cockcroft-Gault CrCl is ${calculatedCrCl} mL/min. Flagged ${interactions.length} drug interaction(s), ${renalAdjustments.length} renal dose adjustment(s), and ${duplicateTherapies.length} duplicate class(es). Overall severity classified as ${overallSeverity}.`;

  return {
    patientId: patient.id,
    timestamp: new Date().toISOString(),
    overallSeverity,
    summary,
    calculatedCrCl,
    calculatedIBW,
    calculatedAdjBW,
    drugInteractions: interactions,
    duplicateTherapies,
    renalDoseAdjustments: renalAdjustments,
    contraindications,
    monitoringPlan,
    patientCounseling,
    clinicalRecommendations
  };
}
